name: "Pull Request Labeler"
on:
- pull_request_target

jobs:
  labeler:
    permissions:
      contents: read
      labels: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - uses: actions/labeler@v6
      with:
        configuration-path: '.github/labeler.yml'
